### ISSUE TITLE
SIGSEGV related to mysqli_query

### ISSUE THREAD

**Issue by jontro** [longxinH/xhprof#16]
Getting the following backtrace

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f79b3a71028 in ?? ()
(gdb) bt
#0  0x00007f79b3a71028 in ?? ()
#1  0x00007f79b37fd2f8 in hp_get_trace_callback (symbol=symbol@entry=0x7f79af668be0 "mysqli_query",
    data=data@entry=0x7f79b3a18070) at /var/www/html/xhprof/extension/xhprof.c:1610
#2  0x00007f79b37fd562 in hp_execute_internal (execute_data=0x7f79b3a18070, return_value=0x7f79b3a179e0)
    at /var/www/html/xhprof/extension/xhprof.c:1136
#3  0x000055576cf49250 in ?? ()
#4  0x000055576cf0536b in execute_ex ()
#5  0x00007f79b37fd411 in hp_execute_ex (execute_data=0x7f79b3a17610)
    at /var/www/html/xhprof/extension/xhprof.c:1107
#6  0x000055576cf49373 in ?? ()
#7  0x000055576cf0536b in execute_ex ()
#8  0x000055576cf5524c in ?? ()
#9  0x000055576cf0536b in execute_ex ()
#10 0x000055576cf5524c in ?? ()
#11 0x000055576cf0536b in execute_ex ()
#12 0x000055576cf558bc in ?? ()
#13 0x000055576cf0536b in execute_ex ()
#14 0x000055576cf587e7 in zend_execute ()
#15 0x000055576cec4513 in zend_execute_scripts ()
#16 0x000055576ce63460 in php_execute_script ()
#17 0x000055576cf5a47c in ?? ()
#18 0x000055576cb58337 in ?? ()
#19 0x00007f79bac7c2e1 in __libc_start_main (main=0x55576cb57ed0, argc=2, argv=0x7fff492e89b8,
    init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fff492e89a8)
    at ../csu/libc-start.c:291
#20 0x000055576cb5847a in _start ()
```

when running with xhprof

```
php -v
PHP 7.0.31 (cli) (built: Sep  5 2018 06:37:24) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
```

**Comment by longxinH** [comment]
What is your xhprof version?

**Comment by longxinH** [comment]
I am very sorry, due to the previous version of the rollback, the master branch code is confusing, you can try the latest master branch or version 2.0.3

**Comment by jontro** [comment]
Thanks!
